---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: instavote-deploy
  namespace: instavote
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: github-instavote-deploy
  url: https://github.com/devopsfoo/instavote-deploy

